"""Stage2 refine_v2 module 1: contact labels, windows, and strict audit."""

from .schema import (
    DEFAULT_GAP_MERGE,
    DEFAULT_PER_HAND_MAX_WINDOWS,
    DEFAULT_PER_SEQ_MAX_WINDOWS,
    DEFAULT_RAW_L_MIN,
    DEFAULT_TAU_CONTACT,
    DEFAULT_WINDOW_SIZE,
    HAND_SIDE_IDS,
    HAND_SIDE_NAMES,
    TARGET_REGION_IDS,
    TARGET_REGION_NAMES,
)

__all__ = [
    "DEFAULT_GAP_MERGE",
    "DEFAULT_PER_HAND_MAX_WINDOWS",
    "DEFAULT_PER_SEQ_MAX_WINDOWS",
    "DEFAULT_RAW_L_MIN",
    "DEFAULT_TAU_CONTACT",
    "DEFAULT_WINDOW_SIZE",
    "HAND_SIDE_IDS",
    "HAND_SIDE_NAMES",
    "TARGET_REGION_IDS",
    "TARGET_REGION_NAMES",
]
