"""Open a refine_v2 refiner visualization pack in aitviewer.

The pack is generated by `python -m refine_v2.cli_export_refiner_vis_pack` and
contains full actor/coarse/refined/GT rot6d sequences plus selector window
annotations. This script does not run the refiner model.
"""

from __future__ import annotations

import argparse
from typing import Any

import numpy as np

from visualize.refine_v2.view_subset_window_ait import (
    _apply_vertex_colors,
    _betas_from_pack,
    _build_highlight_vertex_colors,
    _configure_aitviewer,
    _gender_from_pack,
    _make_sequence,
    _motion_to_smpl_params,
)

ACTOR_COLOR = (0.10, 0.47, 0.78, 1.0)
REACTOR_COLOR = (0.88, 0.30, 0.20, 1.0)


def _load_pack(path: str) -> tuple[dict[str, Any], dict[str, Any]]:
    data = np.load(path, allow_pickle=True)
    pack = {key: data[key] for key in data.files}
    if "manifest_json" in pack:
        manifest = pack["manifest_json"].item()
    else:
        manifest = {"sequences": []}
    return pack, manifest


def _select_sequence(
    manifest: dict[str, Any],
    *,
    sequence_index: int | None,
    dataset_row_index: int | None,
) -> tuple[int, dict[str, Any]]:
    sequences = [dict(item) for item in manifest.get("sequences", [])]
    if not sequences:
        raise ValueError("Visualization pack manifest has no sequences.")
    if dataset_row_index is not None:
        matches = [
            (idx, item)
            for idx, item in enumerate(sequences)
            if int(item.get("dataset_row_index", -1)) == int(dataset_row_index)
        ]
        if not matches:
            raise KeyError(f"dataset_row_index={dataset_row_index} not found in visualization pack.")
        if len(matches) > 1:
            raise ValueError(f"dataset_row_index={dataset_row_index} matched multiple sequences.")
        return int(matches[0][0]), dict(matches[0][1])
    idx = int(sequence_index or 0)
    if idx < 0 or idx >= len(sequences):
        raise IndexError(f"sequence_index out of range: {idx}, total={len(sequences)}")
    return idx, dict(sequences[idx])


def _select_window(
    sequence: dict[str, Any],
    *,
    window_index: int | None,
    sequence_window_index: int | None,
    start_frame: int | None,
) -> dict[str, Any] | None:
    windows = [dict(item) for item in sequence.get("windows", [])]
    if not windows:
        return None
    if window_index is not None:
        matches = [item for item in windows if int(item.get("window_index", -1)) == int(window_index)]
    elif sequence_window_index is not None:
        matches = [item for item in windows if int(item.get("sequence_window_index", -1)) == int(sequence_window_index)]
    elif start_frame is not None:
        matches = [item for item in windows if int(item.get("start_frame", -1)) == int(start_frame)]
    else:
        selected = [item for item in windows if bool(item.get("selected_window", False))]
        matches = selected[:1] if selected else windows[:1]
    if not matches:
        raise KeyError("No window matched the requested selector inside this sequence.")
    if len(matches) > 1:
        preview = ", ".join(
            f"idx={item.get('window_index')} seq_win={item.get('sequence_window_index')} "
            f"[{item.get('start_frame')},{item.get('end_frame')}) hand={item.get('hand_side')}"
            for item in matches[:10]
        )
        raise ValueError(f"Window selector matched {len(matches)} windows. First matches: {preview}")
    return dict(matches[0])


def _params_with_offset(params: dict[str, Any], offset: tuple[float, float, float]) -> dict[str, Any]:
    out = dict(params)
    out["trans"] = np.asarray(params["trans"], dtype=np.float32).copy()
    out["trans"] += np.asarray(offset, dtype=np.float32).reshape(1, 3)
    return out


def _load_exported_baseline_params(baseline_data_dir: str, dataset_key: str) -> tuple[dict[str, Any], dict[str, Any]]:
    clip_dir = os.path.join(os.path.abspath(baseline_data_dir), str(dataset_key))
    p1_path = os.path.join(clip_dir, "P1.npz")
    p2_path = os.path.join(clip_dir, "P2.npz")
    if not os.path.exists(p1_path) or not os.path.exists(p2_path):
        raise FileNotFoundError(
            f"Baseline clip not found for dataset_key={dataset_key} under {baseline_data_dir}. "
            f"Expected {p1_path} and {p2_path}."
        )

    def _params_from_npz(path: str) -> dict[str, Any]:
        data = np.load(path, allow_pickle=True)
        return {
            "root_orient": np.asarray(data["root_orient"], dtype=np.float32),
            "pose_body": np.asarray(data["pose_body"], dtype=np.float32),
            "pose_lhand": np.asarray(data["pose_lhand"], dtype=np.float32),
            "pose_rhand": np.asarray(data["pose_rhand"], dtype=np.float32),
            "trans": np.asarray(data["trans"], dtype=np.float32),
            "betas": np.asarray(data["betas"], dtype=np.float32).reshape(-1)[:10],
            "gender": str(data["gender"].item() if np.asarray(data["gender"]).shape == () else data["gender"]),
            "source_role": str(data["source_role"].item() if np.asarray(data["source_role"]).shape == () else data["source_role"]),
        }

    p1 = _params_from_npz(p1_path)
    p2 = _params_from_npz(p2_path)
    if p1.get("source_role") == "actor":
        return p1, p2
    if p2.get("source_role") == "actor":
        return p2, p1
    raise ValueError(f"Could not infer actor/reactor roles from baseline clip: {clip_dir}")


def _make_panel(
    viewer,
    *,
    actor_params: dict[str, Any],
    reactor_params: dict[str, Any],
    actor_layer,
    reactor_layer,
    device,
    panel_name: str,
    offset: tuple[float, float, float],
    actor_vertex_colors,
    reactor_vertex_colors,
    reactor_color: tuple[float, float, float, float],
):
    actor_seq = _make_sequence(
        _params_with_offset(actor_params, offset),
        smpl_layer=actor_layer,
        device=device,
        color=ACTOR_COLOR,
        name=f"{panel_name}_actor",
    )
    _disable_internal_skeleton(actor_seq)
    _apply_vertex_colors(actor_seq, actor_vertex_colors)
    viewer.scene.add(actor_seq)

    reactor_seq = _make_sequence(
        _params_with_offset(reactor_params, offset),
        smpl_layer=reactor_layer,
        device=device,
        color=reactor_color,
        name=f"{panel_name}_reactor",
    )
    _disable_internal_skeleton(reactor_seq)
    _apply_vertex_colors(reactor_seq, reactor_vertex_colors)
    viewer.scene.add(reactor_seq)
    return [actor_seq, reactor_seq]


def _disable_internal_skeleton(renderable):
    """Best-effort hide aitviewer joint/skeleton helpers across versions."""
    for attr in (
        "skeleton_seq",
        "skeleton",
        "joints_seq",
        "joints",
        "joint_seq",
        "joint_angles_seq",
    ):
        obj = getattr(renderable, attr, None)
        if obj is None:
            continue
        for flag in ("enabled", "visible", "show", "is_visible"):
            if hasattr(obj, flag):
                try:
                    setattr(obj, flag, False)
                except Exception:
                    pass
    for flag in (
        "show_skeleton",
        "show_joints",
        "show_joint_angles",
        "draw_skeleton",
        "draw_joints",
    ):
        if hasattr(renderable, flag):
            try:
                setattr(renderable, flag, False)
            except Exception:
                pass


def open_refiner_vis_pack_viewer(
    *,
    vis_pack_path: str,
    sequence_index: int | None = 0,
    dataset_row_index: int | None = None,
    window_index: int | None = None,
    sequence_window_index: int | None = None,
    start_frame: int | None = None,
    mode: str = "coarse_refined_gt",
    baseline_data_dir: str = "",
    part_segm_path: str = "",
    title: str = "",
    fps: int = 30,
    window_scale: float = 0.9,
    panel_spacing: float = 2.8,
):
    import glfw
    import imgui
    from aitviewer.configuration import CONFIG as C
    from aitviewer.models.smpl import SMPLLayer
    from aitviewer.renderables.plane import Plane
    from aitviewer.viewer import Viewer

    class RefinerVisPackViewer(Viewer):
        title = "refine_v2 refiner visualization pack"

        def __init__(self, *, pack, manifest, initial_sequence_index: int, initial_window_selector: dict[str, Any], **kwargs):
            super().__init__(**kwargs)
            self.pack = pack
            self.manifest = manifest
            self.sequences = [dict(item) for item in manifest.get("sequences", [])]
            self.sequence_index = int(initial_sequence_index)
            self.window_selector = dict(initial_window_selector)
            self.window_index_in_sequence = 0
            self.render_nodes = []
            self.goto_sequence_text = str(self.sequence_index)
            self.goto_window_text = "0"
            self.gui_controls.update({"refine_v2": self.gui_refine_v2})
            keys = self.wnd.keys
            self._next_sequence_keys = [x for x in (getattr(keys, "N", None), getattr(keys, "RIGHT", None)) if x is not None]
            self._prev_sequence_keys = [x for x in (getattr(keys, "P", None), getattr(keys, "LEFT", None)) if x is not None]
            self._next_window_keys = [x for x in (getattr(keys, "J", None), getattr(keys, "DOWN", None)) if x is not None]
            self._prev_window_keys = [x for x in (getattr(keys, "K", None), getattr(keys, "UP", None)) if x is not None]
            self._reset_frame_keys = [x for x in (getattr(keys, "R", None),) if x is not None]

        def on_render(self, time: float, frame_time: float):
            self.render(time, frame_time)

        def key_event(self, key, action, modifiers):
            if action == self.wnd.keys.ACTION_PRESS:
                if key in self._next_sequence_keys:
                    self.set_sequence(self.sequence_index + 1)
                    return
                if key in self._prev_sequence_keys:
                    self.set_sequence(self.sequence_index - 1)
                    return
                if key in self._next_window_keys:
                    self.set_window(self.window_index_in_sequence + 1)
                    return
                if key in self._prev_window_keys:
                    self.set_window(self.window_index_in_sequence - 1)
                    return
                if key in self._reset_frame_keys:
                    self.reset_to_window_start()
                    return
            return super().key_event(key, action, modifiers)

        def clear_sequence(self):
            for node in list(self.render_nodes):
                try:
                    self.scene.remove(node)
                except Exception:
                    pass
            self.render_nodes = []

        def set_sequence(self, idx: int):
            self.sequence_index = int(idx) % max(1, len(self.sequences))
            self.window_index_in_sequence = 0
            self.goto_sequence_text = str(self.sequence_index)
            self.load_sequence()

        def set_window(self, idx: int):
            sequence = self.current_sequence()
            windows = list(sequence.get("windows", []))
            if not windows:
                self.window_index_in_sequence = 0
                return
            self.window_index_in_sequence = int(idx) % len(windows)
            self.goto_window_text = str(self.window_index_in_sequence)
            self.reset_to_window_start()
            self.print_current_info()

        def current_sequence(self) -> dict[str, Any]:
            return dict(self.sequences[self.sequence_index])

        def current_window(self) -> dict[str, Any] | None:
            windows = [dict(item) for item in self.current_sequence().get("windows", [])]
            if not windows:
                return None
            self.window_index_in_sequence = int(self.window_index_in_sequence) % len(windows)
            return dict(windows[self.window_index_in_sequence])

        def reset_to_window_start(self):
            window = self.current_window()
            sequence = self.current_sequence()
            length = int(sequence.get("length", np.asarray(self.pack["lengths"])[self.sequence_index]))
            frame = int(window.get("start_frame", 0)) if window else 0
            self.scene.current_frame_id = max(0, min(frame, max(0, length - 1)))

        def sequence_params(self, field: str, seq_idx: int, length: int, betas_key: str, gender_key: str):
            return _motion_to_smpl_params(
                np.asarray(self.pack[field][seq_idx], dtype=np.float32),
                start=0,
                end=length,
                betas=_betas_from_pack(self.pack, betas_key, seq_idx),
                gender=_gender_from_pack(self.pack, gender_key, seq_idx),
            )

        def load_sequence(self):
            self.clear_sequence()
            seq_idx = int(self.sequence_index)
            sequence = self.current_sequence()
            length = int(sequence.get("length", np.asarray(self.pack["lengths"])[seq_idx]))
            actor_params = self.sequence_params("actor_motion", seq_idx, length, "actor_betas", "actor_gender_id")
            coarse_params = self.sequence_params("reactor_coarse_motion", seq_idx, length, "reactor_betas", "reactor_gender_id")
            refined_params = self.sequence_params("reactor_refined_motion", seq_idx, length, "reactor_betas", "reactor_gender_id")
            gt_params = self.sequence_params("reactor_gt_motion", seq_idx, length, "reactor_betas", "reactor_gender_id")
            baseline_actor_params = None
            baseline_reactor_params = None
            if baseline_data_dir:
                baseline_actor_params, baseline_reactor_params = _load_exported_baseline_params(
                    baseline_data_dir,
                    str(sequence.get("dataset_key")),
                )

            actor_layer = SMPLLayer(model_type="smplx", gender=actor_params["gender"], num_betas=10, device=C.device)
            reactor_layer = SMPLLayer(model_type="smplx", gender=gt_params["gender"], num_betas=10, device=C.device)
            window = self.current_window()
            primary = str(window.get("primary_target_region", "")) if window and part_segm_path else ""
            topk = [str(x) for x in window.get("topk_target_regions", [])] if window and part_segm_path else []
            hand_side = str(window.get("hand_side", "")) if window and part_segm_path else ""
            actor_vertex_colors = _build_highlight_vertex_colors(
                actor_layer,
                part_segm_path,
                base_color=ACTOR_COLOR,
                primary_region=primary,
                topk_regions=topk,
            )
            reactor_vertex_colors = _build_highlight_vertex_colors(
                reactor_layer,
                part_segm_path,
                base_color=REACTOR_COLOR,
                primary_region=f"{hand_side}_hand" if hand_side else "",
                topk_regions=[],
            )

            if mode == "coarse_refined_gt":
                panels = [
                    ("coarse", actor_params, coarse_params, (-float(panel_spacing), 0.0, 0.0)),
                    ("refined", actor_params, refined_params, (0.0, 0.0, 0.0)),
                    ("gt", actor_params, gt_params, (float(panel_spacing), 0.0, 0.0)),
                ]
            elif mode == "baseline_coarse_refined_gt":
                if not baseline_data_dir or baseline_actor_params is None or baseline_reactor_params is None:
                    raise ValueError("--mode baseline_coarse_refined_gt requires --baseline_data_dir")
                panels = [
                    ("baseline", baseline_actor_params, baseline_reactor_params, (-1.5 * float(panel_spacing), 0.0, 0.0)),
                    ("coarse", actor_params, coarse_params, (-0.5 * float(panel_spacing), 0.0, 0.0)),
                    ("refined", actor_params, refined_params, (0.5 * float(panel_spacing), 0.0, 0.0)),
                    ("gt", actor_params, gt_params, (1.5 * float(panel_spacing), 0.0, 0.0)),
                ]
            elif mode == "coarse":
                panels = [("coarse", actor_params, coarse_params, (0.0, 0.0, 0.0))]
            elif mode == "refined":
                panels = [("refined", actor_params, refined_params, (0.0, 0.0, 0.0))]
            elif mode == "baseline":
                if not baseline_data_dir or baseline_actor_params is None or baseline_reactor_params is None:
                    raise ValueError("--mode baseline requires --baseline_data_dir")
                panels = [("baseline", baseline_actor_params, baseline_reactor_params, (0.0, 0.0, 0.0))]
            else:
                panels = [("gt", actor_params, gt_params, (0.0, 0.0, 0.0))]

            for panel_name, panel_actor_params, panel_reactor_params, offset in panels:
                self.render_nodes.extend(
                    _make_panel(
                        self,
                        actor_params=panel_actor_params,
                        reactor_params=panel_reactor_params,
                        actor_layer=actor_layer,
                        reactor_layer=reactor_layer,
                        device=C.device,
                        panel_name=panel_name,
                        offset=offset,
                        actor_vertex_colors=actor_vertex_colors,
                        reactor_vertex_colors=reactor_vertex_colors,
                        reactor_color=REACTOR_COLOR,
                    )
                )
            self.reset_to_window_start()
            self.print_current_info()

        def info_lines(self) -> list[str]:
            sequence = self.current_sequence()
            window = self.current_window()
            lines = [
                f"sequence: {self.sequence_index + 1}/{len(self.sequences)}",
                f"dataset_row_index: {sequence.get('dataset_row_index')}",
                f"dataset_key: {sequence.get('dataset_key')}",
                f"action_type: {sequence.get('action_type')}",
                f"length: {sequence.get('length')}",
                f"mode: {mode}",
                "keys: N/right next seq, P/left prev seq, J/down next window, K/up prev window, R reset frame",
            ]
            if window:
                lines.extend(
                    [
                        f"window: {self.window_index_in_sequence + 1}/{len(sequence.get('windows', []))}",
                        f"window_index: {window.get('window_index')}",
                        f"range: [{window.get('start_frame')},{window.get('end_frame')})",
                        f"hand: {window.get('hand_side')}",
                        f"primary: {window.get('primary_target_region')}",
                        f"topk: {window.get('topk_target_regions')}",
                    ]
                )
            return lines

        def print_current_info(self):
            print("\n".join(["", "refine_v2 vis pack"] + self.info_lines()), flush=True)

        def gui_refine_v2(self):
            imgui.set_next_window_position(self.window_size[0] * 0.62, self.window_size[1] * 0.08, imgui.FIRST_USE_EVER)
            imgui.set_next_window_size(self.window_size[0] * 0.34, self.window_size[1] * 0.42, imgui.FIRST_USE_EVER)
            expanded, _ = imgui.begin("refine_v2 controls", None)
            if expanded:
                if imgui.button("Prev Seq"):
                    self.set_sequence(self.sequence_index - 1)
                imgui.same_line()
                if imgui.button("Next Seq"):
                    self.set_sequence(self.sequence_index + 1)
                imgui.same_line()
                if imgui.button("Reset Frame"):
                    self.reset_to_window_start()

                if imgui.button("Prev Window"):
                    self.set_window(self.window_index_in_sequence - 1)
                imgui.same_line()
                if imgui.button("Next Window"):
                    self.set_window(self.window_index_in_sequence + 1)

                imgui.text("Go to sequence index")
                imgui.set_next_item_width(imgui.get_window_width() * 0.35)
                _, self.goto_sequence_text = imgui.input_text("##goto_seq", self.goto_sequence_text)
                imgui.same_line()
                if imgui.button("Go Seq"):
                    try:
                        self.set_sequence(int(self.goto_sequence_text))
                    except Exception:
                        pass

                imgui.text("Go to window-in-sequence index")
                imgui.set_next_item_width(imgui.get_window_width() * 0.35)
                _, self.goto_window_text = imgui.input_text("##goto_window", self.goto_window_text)
                imgui.same_line()
                if imgui.button("Go Window"):
                    try:
                        self.set_window(int(self.goto_window_text))
                    except Exception:
                        pass

                imgui.separator()
                for line in self.info_lines():
                    imgui.text_wrapped(str(line))
            imgui.end()

    _configure_aitviewer(C, glfw, window_scale=window_scale)
    pack, manifest = _load_pack(vis_pack_path)
    seq_idx, _ = _select_sequence(
        manifest,
        sequence_index=sequence_index,
        dataset_row_index=dataset_row_index,
    )
    initial_sequence = dict(manifest.get("sequences", [])[seq_idx])
    initial_window = _select_window(
        initial_sequence,
        window_index=window_index,
        sequence_window_index=sequence_window_index,
        start_frame=start_frame,
    )
    initial_window_index = 0
    if initial_window is not None:
        for i, item in enumerate(initial_sequence.get("windows", [])):
            if dict(item) == initial_window:
                initial_window_index = i
                break
    viewer_title = title or (
        f"refine_v2 row={initial_sequence.get('dataset_row_index')} "
        f"{initial_sequence.get('action_type', '')} seq={seq_idx}"
    )
    viewer = RefinerVisPackViewer(
        title=viewer_title,
        pack=pack,
        manifest=manifest,
        initial_sequence_index=seq_idx,
        initial_window_selector={
            "window_index": window_index,
            "sequence_window_index": sequence_window_index,
            "start_frame": start_frame,
        },
    )
    viewer.scene.fps = int(fps)
    viewer.playback_fps = int(fps)

    try:
        viewer.scene.add(Plane(color=(0.45, 0.45, 0.45, 0.35)))
    except Exception:
        pass
    viewer.window_index_in_sequence = int(initial_window_index)
    viewer.load_sequence()
    viewer.run()


def build_parser():
    parser = argparse.ArgumentParser(description="Open a refine_v2 refiner visualization pack in aitviewer.")
    parser.add_argument("--vis_pack_path", required=True)
    parser.add_argument("--sequence_index", type=int, default=0)
    parser.add_argument("--dataset_row_index", type=int, default=None)
    parser.add_argument("--window_index", type=int, default=None)
    parser.add_argument("--sequence_window_index", type=int, default=None)
    parser.add_argument("--start_frame", type=int, default=None)
    parser.add_argument(
        "--mode",
        choices=["coarse", "refined", "gt", "baseline", "coarse_refined_gt", "baseline_coarse_refined_gt"],
        default="coarse_refined_gt",
    )
    parser.add_argument(
        "--baseline_data_dir",
        default="",
        help="Optional root containing exported baseline clips as <baseline_data_dir>/<dataset_key>/{P1,P2}.npz",
    )
    parser.add_argument("--part_segm_path", default="")
    parser.add_argument("--title", default="")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--window_scale", type=float, default=0.9)
    parser.add_argument("--panel_spacing", type=float, default=2.8)
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    open_refiner_vis_pack_viewer(
        vis_pack_path=args.vis_pack_path,
        sequence_index=args.sequence_index,
        dataset_row_index=args.dataset_row_index,
        window_index=args.window_index,
        sequence_window_index=args.sequence_window_index,
        start_frame=args.start_frame,
        mode=args.mode,
        baseline_data_dir=args.baseline_data_dir,
        part_segm_path=args.part_segm_path,
        title=args.title,
        fps=args.fps,
        window_scale=args.window_scale,
        panel_spacing=args.panel_spacing,
    )


if __name__ == "__main__":
    main()
