"""Open a refine_v2 refiner visualization pack in aitviewer.

The pack is generated by `python -m refine_v2.cli_export_refiner_vis_pack` and
contains full actor/coarse/refined/GT rot6d sequences plus selector window
annotations. This script does not run the refiner model.
"""

from __future__ import annotations

import argparse
from typing import Any

import numpy as np

from visualize.refine_v2.view_subset_window_ait import (
    _apply_vertex_colors,
    _betas_from_pack,
    _build_highlight_vertex_colors,
    _configure_aitviewer,
    _gender_from_pack,
    _make_sequence,
    _motion_to_smpl_params,
)


def _load_pack(path: str) -> tuple[dict[str, Any], dict[str, Any]]:
    data = np.load(path, allow_pickle=True)
    pack = {key: data[key] for key in data.files}
    if "manifest_json" in pack:
        manifest = pack["manifest_json"].item()
    else:
        manifest = {"sequences": []}
    return pack, manifest


def _select_sequence(
    manifest: dict[str, Any],
    *,
    sequence_index: int | None,
    dataset_row_index: int | None,
) -> tuple[int, dict[str, Any]]:
    sequences = [dict(item) for item in manifest.get("sequences", [])]
    if not sequences:
        raise ValueError("Visualization pack manifest has no sequences.")
    if dataset_row_index is not None:
        matches = [
            (idx, item)
            for idx, item in enumerate(sequences)
            if int(item.get("dataset_row_index", -1)) == int(dataset_row_index)
        ]
        if not matches:
            raise KeyError(f"dataset_row_index={dataset_row_index} not found in visualization pack.")
        if len(matches) > 1:
            raise ValueError(f"dataset_row_index={dataset_row_index} matched multiple sequences.")
        return int(matches[0][0]), dict(matches[0][1])
    idx = int(sequence_index or 0)
    if idx < 0 or idx >= len(sequences):
        raise IndexError(f"sequence_index out of range: {idx}, total={len(sequences)}")
    return idx, dict(sequences[idx])


def _select_window(
    sequence: dict[str, Any],
    *,
    window_index: int | None,
    sequence_window_index: int | None,
    start_frame: int | None,
) -> dict[str, Any] | None:
    windows = [dict(item) for item in sequence.get("windows", [])]
    if not windows:
        return None
    if window_index is not None:
        matches = [item for item in windows if int(item.get("window_index", -1)) == int(window_index)]
    elif sequence_window_index is not None:
        matches = [item for item in windows if int(item.get("sequence_window_index", -1)) == int(sequence_window_index)]
    elif start_frame is not None:
        matches = [item for item in windows if int(item.get("start_frame", -1)) == int(start_frame)]
    else:
        selected = [item for item in windows if bool(item.get("selected_window", False))]
        matches = selected[:1] if selected else windows[:1]
    if not matches:
        raise KeyError("No window matched the requested selector inside this sequence.")
    if len(matches) > 1:
        preview = ", ".join(
            f"idx={item.get('window_index')} seq_win={item.get('sequence_window_index')} "
            f"[{item.get('start_frame')},{item.get('end_frame')}) hand={item.get('hand_side')}"
            for item in matches[:10]
        )
        raise ValueError(f"Window selector matched {len(matches)} windows. First matches: {preview}")
    return dict(matches[0])


def _params_with_offset(params: dict[str, Any], offset: tuple[float, float, float]) -> dict[str, Any]:
    out = dict(params)
    out["trans"] = np.asarray(params["trans"], dtype=np.float32).copy()
    out["trans"] += np.asarray(offset, dtype=np.float32).reshape(1, 3)
    return out


def _make_panel(
    viewer,
    *,
    actor_params: dict[str, Any],
    reactor_params: dict[str, Any],
    actor_layer,
    reactor_layer,
    device,
    panel_name: str,
    offset: tuple[float, float, float],
    actor_vertex_colors,
    reactor_vertex_colors,
    reactor_color: tuple[float, float, float, float],
):
    actor_seq = _make_sequence(
        _params_with_offset(actor_params, offset),
        smpl_layer=actor_layer,
        device=device,
        color=(0.10, 0.47, 0.78, 0.65),
        name=f"{panel_name}_actor",
    )
    _apply_vertex_colors(actor_seq, actor_vertex_colors)
    viewer.scene.add(actor_seq)

    reactor_seq = _make_sequence(
        _params_with_offset(reactor_params, offset),
        smpl_layer=reactor_layer,
        device=device,
        color=reactor_color,
        name=f"{panel_name}_reactor",
    )
    _apply_vertex_colors(reactor_seq, reactor_vertex_colors)
    viewer.scene.add(reactor_seq)


def open_refiner_vis_pack_viewer(
    *,
    vis_pack_path: str,
    sequence_index: int | None = 0,
    dataset_row_index: int | None = None,
    window_index: int | None = None,
    sequence_window_index: int | None = None,
    start_frame: int | None = None,
    mode: str = "coarse_refined_gt",
    part_segm_path: str = "",
    title: str = "",
    fps: int = 30,
    window_scale: float = 0.9,
    panel_spacing: float = 2.8,
):
    import glfw
    from aitviewer.configuration import CONFIG as C
    from aitviewer.models.smpl import SMPLLayer
    from aitviewer.renderables.plane import Plane
    from aitviewer.viewer import Viewer

    class RefinerVisPackViewer(Viewer):
        title = "refine_v2 refiner visualization pack"

        def on_render(self, time: float, frame_time: float):
            self.render(time, frame_time)

    pack, manifest = _load_pack(vis_pack_path)
    seq_idx, sequence = _select_sequence(
        manifest,
        sequence_index=sequence_index,
        dataset_row_index=dataset_row_index,
    )
    window = _select_window(
        sequence,
        window_index=window_index,
        sequence_window_index=sequence_window_index,
        start_frame=start_frame,
    )
    length = int(sequence.get("length", np.asarray(pack["lengths"])[seq_idx]))
    start = 0
    end = length

    actor_params = _motion_to_smpl_params(
        np.asarray(pack["actor_motion"][seq_idx], dtype=np.float32),
        start=start,
        end=end,
        betas=_betas_from_pack(pack, "actor_betas", seq_idx),
        gender=_gender_from_pack(pack, "actor_gender_id", seq_idx),
    )
    coarse_params = _motion_to_smpl_params(
        np.asarray(pack["reactor_coarse_motion"][seq_idx], dtype=np.float32),
        start=start,
        end=end,
        betas=_betas_from_pack(pack, "reactor_betas", seq_idx),
        gender=_gender_from_pack(pack, "reactor_gender_id", seq_idx),
    )
    refined_params = _motion_to_smpl_params(
        np.asarray(pack["reactor_refined_motion"][seq_idx], dtype=np.float32),
        start=start,
        end=end,
        betas=_betas_from_pack(pack, "reactor_betas", seq_idx),
        gender=_gender_from_pack(pack, "reactor_gender_id", seq_idx),
    )
    gt_params = _motion_to_smpl_params(
        np.asarray(pack["reactor_gt_motion"][seq_idx], dtype=np.float32),
        start=start,
        end=end,
        betas=_betas_from_pack(pack, "reactor_betas", seq_idx),
        gender=_gender_from_pack(pack, "reactor_gender_id", seq_idx),
    )

    _configure_aitviewer(C, glfw, window_scale=window_scale)
    viewer_title = title or (
        f"refine_v2 row={sequence.get('dataset_row_index')} "
        f"{sequence.get('action_type', '')} seq={seq_idx}"
    )
    viewer = RefinerVisPackViewer(title=viewer_title)
    viewer.scene.fps = int(fps)
    viewer.playback_fps = int(fps)

    current_frame = int(window.get("start_frame", 0)) if window else int(start_frame or 0)
    viewer.scene.current_frame_id = max(0, min(current_frame, length - 1))

    actor_layer = SMPLLayer(model_type="smplx", gender=actor_params["gender"], num_betas=10, device=C.device)
    reactor_layer = SMPLLayer(model_type="smplx", gender=gt_params["gender"], num_betas=10, device=C.device)

    primary = str(window.get("primary_target_region", "")) if window else ""
    topk = [str(x) for x in window.get("topk_target_regions", [])] if window else []
    hand_side = str(window.get("hand_side", "")) if window else ""
    actor_vertex_colors = _build_highlight_vertex_colors(
        actor_layer,
        part_segm_path,
        base_color=(0.10, 0.47, 0.78, 0.65),
        primary_region=primary,
        topk_regions=topk,
    )
    reactor_vertex_colors = _build_highlight_vertex_colors(
        reactor_layer,
        part_segm_path,
        base_color=(0.88, 0.30, 0.20, 0.82),
        primary_region=f"{hand_side}_hand" if hand_side else "",
        topk_regions=[],
    )

    if mode == "coarse_refined_gt":
        panels = [
            ("coarse", coarse_params, (-float(panel_spacing), 0.0, 0.0), (0.90, 0.32, 0.18, 0.82)),
            ("refined", refined_params, (0.0, 0.0, 0.0), (0.25, 0.75, 0.35, 0.82)),
            ("gt", gt_params, (float(panel_spacing), 0.0, 0.0), (0.15, 0.72, 0.90, 0.82)),
        ]
    elif mode == "coarse":
        panels = [("coarse", coarse_params, (0.0, 0.0, 0.0), (0.90, 0.32, 0.18, 0.82))]
    elif mode == "refined":
        panels = [("refined", refined_params, (0.0, 0.0, 0.0), (0.25, 0.75, 0.35, 0.82))]
    else:
        panels = [("gt", gt_params, (0.0, 0.0, 0.0), (0.15, 0.72, 0.90, 0.82))]

    for panel_name, params, offset, color in panels:
        _make_panel(
            viewer,
            actor_params=actor_params,
            reactor_params=params,
            actor_layer=actor_layer,
            reactor_layer=reactor_layer,
            device=C.device,
            panel_name=panel_name,
            offset=offset,
            actor_vertex_colors=actor_vertex_colors,
            reactor_vertex_colors=reactor_vertex_colors,
            reactor_color=color,
        )

    try:
        viewer.scene.add(Plane(color=(0.45, 0.45, 0.45, 0.35)))
    except Exception:
        pass

    print("opening refine_v2 refiner vis pack")
    print(f"vis_pack_path: {vis_pack_path}")
    print(f"sequence_index: {seq_idx}")
    print(f"dataset_row_index: {sequence.get('dataset_row_index')}")
    print(f"dataset_key: {sequence.get('dataset_key')}")
    print(f"action_type: {sequence.get('action_type')}")
    print(f"length: {length}")
    print(f"mode: {mode}")
    if window:
        print("selected window:")
        print(f"  window_index: {window.get('window_index')}")
        print(f"  sequence_window_index: {window.get('sequence_window_index')}")
        print(f"  range: [{window.get('start_frame')},{window.get('end_frame')})")
        print(f"  hand_side: {window.get('hand_side')}")
        print(f"  primary_target_region: {primary}")
        print(f"  topk_target_regions: {topk}")
    print("all windows in sequence:")
    for item in sequence.get("windows", []):
        print(
            f"  idx={item.get('window_index')} seq_win={item.get('sequence_window_index')} "
            f"[{item.get('start_frame')},{item.get('end_frame')}) "
            f"hand={item.get('hand_side')} primary={item.get('primary_target_region')} "
            f"topk={item.get('topk_target_regions')}"
        )
    viewer.run()


def build_parser():
    parser = argparse.ArgumentParser(description="Open a refine_v2 refiner visualization pack in aitviewer.")
    parser.add_argument("--vis_pack_path", required=True)
    parser.add_argument("--sequence_index", type=int, default=0)
    parser.add_argument("--dataset_row_index", type=int, default=None)
    parser.add_argument("--window_index", type=int, default=None)
    parser.add_argument("--sequence_window_index", type=int, default=None)
    parser.add_argument("--start_frame", type=int, default=None)
    parser.add_argument("--mode", choices=["coarse", "refined", "gt", "coarse_refined_gt"], default="coarse_refined_gt")
    parser.add_argument("--part_segm_path", default="")
    parser.add_argument("--title", default="")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--window_scale", type=float, default=0.9)
    parser.add_argument("--panel_spacing", type=float, default=2.8)
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    open_refiner_vis_pack_viewer(
        vis_pack_path=args.vis_pack_path,
        sequence_index=args.sequence_index,
        dataset_row_index=args.dataset_row_index,
        window_index=args.window_index,
        sequence_window_index=args.sequence_window_index,
        start_frame=args.start_frame,
        mode=args.mode,
        part_segm_path=args.part_segm_path,
        title=args.title,
        fps=args.fps,
        window_scale=args.window_scale,
        panel_spacing=args.panel_spacing,
    )


if __name__ == "__main__":
    main()
